### ISSUE TITLE
Fallout 2 support

### ISSUE THREAD

**Issue by tagaziel** [sowcow/fallout-dialogs#6]
Perhaps a little more complex, but would it be possible to apply this to Fallout 2 dialogues as well? That would be of tremendous help.

**Comment by sowcow** [comment]
I'm looking into updating this project so with some degree of completeness it should be possible. Sorry for the late reply.

**Comment by tagaziel** [comment]
No worries, glad to see it's still alive! I was thinking about linking to dialogue files from the Fallout Wiki natively, and any help I can provide (keeping in mind I'm a writer, not a programmer), just ask. I know that the major difference is that Fo2 is more sophisticated and uses aliases - don't remember the name off the top of my head, typing up while at my wife's 36th bd - so that might require a little more finagling. It does have more complete documentation in the Mapper.

**Comment by sowcow** [comment]
The idea periodically gets alive but I'm not consistent in execution. Anyway I updated the project, added F2 and some translations I had at hand. Also added readme.

Here are svg digram files that can be used somewhere like wiki: https://github.com/sowcow/fallout-dialogs/tree/master/generated/en-f2-gog/viz

One disclaimer is that these diagrams are incomplete because some dialog branches may depend on calculations involving random for example and such. And this project only shows branches that are referenced by simple number only.

Anyway these svg files are potentially incomplete extracts from both dialogue files (MSG) and scripts(ssl decompiled files) combined.

**Comment by sowcow** [comment]
Concerning writing, my idea was to move this content into something close to textual interactive fiction file format. But possibly with complexity that starts demanding visual editor like those diagrams at some point.

**Comment by tagaziel** [comment]
The graphs are awesome even now. For the branches and calculations, one infamous will be the Cat's Paw (Miss Kitty) dialogue, which inserts the cost of the 'service' between two lines, which is calculated on the fly. And bugged in the release version. We've added a page for the Resources! 

https://fallout.fandom.com/wiki/Resources:Fallout_and_Fallout_2_dialog_graphs

Since Fo2 support is complete, I'll close the issue. Better clear them out, right?

**Comment by sowcow** [comment]
Awesome, feel free to create an issue if there is some significant lacking (possibly the whole characters). But I may generate such list by myself later to see what to do with them.
